channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - pip:
    - matplotlib==3.7.3
    - molmass==2023.4.10
    - numpy==1.24.4
    - pandas==2.0.3
    - pyteomics==4.6.2
    - scipy==1.10.1
    - lxml==4.9.4
    - rdkit==2024.3.5
    - msbuddy==0.3.7